import {
    Eld1, Eld2, Eld3, Eld4, Eld5, 
    Ellen1, Ellen2, Ellen3, Ellen4, 
    image1, image2, image3, image4, image5, image6, 
    io, 
    asare1, asare2, asare3, asare4, 
    kusi1, kusi2, kusi3, kusi4, 
    nyame1, nyame2, nyame3, 
    prampram1, prampram2, prampram3, prampram4, 
    shef1, shef2, shef3, shef4, shef5, shef6
} 
from '../../assets/index'

export const data = [
    { id: 1, image: Eld1 },
    { id: 2, image: Eld2 },
    { id: 3, image: Eld3 },
    { id: 4, image: Eld4 },
    { id: 5, image: Eld5 },
    { id: 6, image: Ellen1 },
    { id: 7, image: Ellen2 },
    { id: 8, image: Ellen3 },
    { id: 9, image: Ellen4 },
    { id: 10, image: image1 },
    { id: 11, image: image2 },
    { id: 12, image: image3 },
    { id: 13, image: image4 },
    { id: 14, image: image5 },
    { id: 15, image: image6 },
    { id: 16, image: io },
    { id: 17, image: asare1 },
    { id: 18, image: asare2 },
    { id: 19, image: asare3 },
    { id: 20, image: asare4 },
    { id: 21, image: kusi1 },
    { id: 22, image: kusi2 },
    { id: 23, image: kusi3 },
    { id: 24, image: kusi4 },
    { id: 25, image: nyame1 },
    { id: 26, image: nyame2 },
    { id: 27, image: nyame3 },
    { id: 28, image: prampram1 },
    { id: 29, image: prampram2 },
    { id: 30, image: prampram3 },
    { id: 31, image: prampram4 },
    { id: 32, image: shef1 },
    { id: 33, image: shef2 },
    { id: 34, image: shef3 },
    { id: 35, image: shef4 },
    { id: 36, image: shef5 },
    { id: 37, image: shef6 },
  ];
  
  